language: node_js
sudo: false
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
env:
  global:
node_js: 4
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
